#!/bin/bash
# bufr - convert files to BUFR
#
# Copyright (C) 2017  ARPA-SIM <urpsimc@arpae.it>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Author: Emanuele Di Giacomo <edigiacomo@arpae.it>

print_usage()
{
    printf "Usage $0 [QUERY]...\n"
}

if [ x"$ARKI_XARGS_FORMAT" == x ]
then
    exec arki-xargs -s 1M -- $0 $@
fi

tempfile="$(mktemp --suffix .sqlite3)" || exit 1

cleanup() { 
    rm -f "${tempfile}"
}

trap cleanup EXIT

bufrfile="${@: -1}"
queries="${@:1:$(($#-1))}"

dbadb import --fast --overwrite --wipe-first --dsn=sqlite:${tempfile} $bufrfile
dbadb export --dsn=sqlite:${tempfile} $queries
